// Predefined credentials (multiple users)
const VALID_USERS = [
    { username: "student", password: "pass123" },
    { username: "kristine", password: "ilovestudying" },
    { username: "rain", password: "pogiako123" },
    { username: "kurt", password: "1234567" },
    { username: "kavin", password: "mynameistrese" }
];


// Storage for attendance records
let attendanceRecords = [];

// Audio context for beep sound
let audioContext;

/**
 * Play beep sound when password is incorrect
 * Plays 3 beeps in succession and shows visual indicator
 */
function playBeep() {
    // Show visual beep indicator
    const beepIndicator = document.getElementById('beepIndicator');
    beepIndicator.style.display = 'block';
    setTimeout(() => {
        beepIndicator.style.display = 'none';
    }, 1500);

    // Play beep sound 3 times for emphasis
    let beepCount = 0;
    const beepInterval = setInterval(() => {
        try {
            const beep = new Audio('beep.mp3');
            beep.play().catch(() => {
                generateBeep();
            });
        } catch (e) {
            generateBeep();
        }
        
        beepCount++;
        if (beepCount >= 3) {
            clearInterval(beepInterval);
        }
    }, 200);
}

/**
 * Generate a beep sound using Web Audio API
 * Used as fallback when beep.mp3 is not available
 */
function generateBeep() {
    if (!audioContext) {
        audioContext = new (window.AudioContext || window.webkitAudioContext)();
    }
    
    const oscillator = audioContext.createOscillator();
    const gainNode = audioContext.createGain();
    
    oscillator.connect(gainNode);
    gainNode.connect(audioContext.destination);
    
    oscillator.frequency.value = 800; // Frequency in Hz
    oscillator.type = 'sine';
    
    gainNode.gain.setValueAtTime(0.3, audioContext.currentTime);
    gainNode.gain.exponentialRampToValueAtTime(0.01, audioContext.currentTime + 0.5);
    
    oscillator.start(audioContext.currentTime);
    oscillator.stop(audioContext.currentTime + 0.5);
}

/**
 * Format a Date object into readable timestamp
 * @param {Date} date - The date to format
 * @returns {string} Formatted timestamp (MM/DD/YYYY HH:MM:SS)
 */
function formatTimestamp(date) {
    const month = String(date.getMonth() + 1).padStart(2, '0');
    const day = String(date.getDate()).padStart(2, '0');
    const year = date.getFullYear();
    const hours = String(date.getHours()).padStart(2, '0');
    const minutes = String(date.getMinutes()).padStart(2, '0');
    const seconds = String(date.getSeconds()).padStart(2, '0');
    
    return `${month}/${day}/${year} ${hours}:${minutes}:${seconds}`;
}

/**
 * Display a message to the user
 * @param {string} text - Message text
 * @param {string} type - Message type ('success' or 'error')
 */
function showMessage(text, type) {
    const messageDiv = document.getElementById('message');
    messageDiv.textContent = text;
    messageDiv.className = `message ${type}`;
    messageDiv.style.display = 'block';
    
    if (type === 'error') {
        setTimeout(() => {
            messageDiv.style.display = 'none';
        }, 3000);
    }
}

/**
 * Show the attendance section after successful login
 * @param {string} username - The logged in username
 * @param {string} timestamp - The login timestamp
 */
function showAttendanceSection(username, timestamp) {
    document.getElementById('loginForm').style.display = 'none';
    document.querySelector('.hint').style.display = 'none';
    document.getElementById('attendanceSection').style.display = 'block';
    document.getElementById('displayUsername').textContent = username;
    document.getElementById('displayTimestamp').textContent = timestamp;
}

/**
 * Reset the form to initial state (logout)
 */
function resetForm() {
    document.getElementById('loginForm').style.display = 'block';
    document.querySelector('.hint').style.display = 'block';
    document.getElementById('attendanceSection').style.display = 'none';
    document.getElementById('message').style.display = 'none';
    document.getElementById('username').value = '';
    document.getElementById('password').value = '';
}

/**
 * Generate a formatted attendance summary report
 * @param {string} username - The username
 * @param {string} timestamp - The login timestamp
 * @returns {string} Formatted attendance summary
 */
function generateAttendanceSummary(username, timestamp) {
    const now = new Date();
    const reportDate = formatTimestamp(now);
    
    let summary = "╔═══════════════════════════════════════════════════════════╗\n";
    summary += "║           ATTENDANCE SUMMARY REPORT                       ║\n";
    summary += "║           Generated by Attendance System                  ║\n";
    summary += "╚═══════════════════════════════════════════════════════════╝\n\n";
    
    summary += "┌───────────────────────────────────────────────────────────┐\n";
    summary += "│ CURRENT LOGIN INFORMATION                                 │\n";
    summary += "└───────────────────────────────────────────────────────────┘\n\n";
    summary += `  👤 Username:        ${username}\n`;
    summary += `  🕐 Login Time:      ${timestamp}\n`;
    summary += `  ✅ Status:          PRESENT\n`;
    summary += `  📍 Session ID:      ${Date.now()}\n\n`;
    
    summary += "┌───────────────────────────────────────────────────────────┐\n";
    summary += "│ ALL ATTENDANCE RECORDS (This Session)                     │\n";
    summary += "└───────────────────────────────────────────────────────────┘\n\n";
    
    if (attendanceRecords.length > 0) {
        attendanceRecords.forEach((record, index) => {
            summary += `  ${String(index + 1).padStart(2, '0')}. ${record.username.padEnd(20)} | ${record.timestamp}\n`;
        });
    } else {
        summary += "  No records available.\n";
    }
    
    summary += "\n┌───────────────────────────────────────────────────────────┐\n";
    summary += "│ SUMMARY STATISTICS                                        │\n";
    summary += "└───────────────────────────────────────────────────────────┘\n\n";
    summary += `  📊 Total Logins:    ${attendanceRecords.length}\n`;
    summary += `  📅 Report Date:     ${reportDate}\n`;
    summary += `  🖥️  System:          Web-Based Attendance System v1.0\n\n`;
    
    summary += "─────────────────────────────────────────────────────────────\n";
    summary += "End of Report\n";
    summary += "─────────────────────────────────────────────────────────────\n";
    
    return summary;
}

/**
 * Download the attendance summary as a text file
 * @param {string} username - The username
 * @param {string} timestamp - The login timestamp
 */
function downloadAttendanceFile(username, timestamp) {
    const attendanceData = generateAttendanceSummary(username, timestamp);
    const blob = new Blob([attendanceData], { type: 'text/plain' });
    const link = document.createElement('a');
    link.href = window.URL.createObjectURL(blob);
    
    // Create filename with timestamp
    const now = new Date();
    const fileTimestamp = `${now.getFullYear()}${String(now.getMonth()+1).padStart(2,'0')}${String(now.getDate()).padStart(2,'0')}_${String(now.getHours()).padStart(2,'0')}${String(now.getMinutes()).padStart(2,'0')}${String(now.getSeconds()).padStart(2,'0')}`;
    link.download = `Attendance_Records/attendance_summary_${username}_${fileTimestamp}.txt`;
    
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    window.URL.revokeObjectURL(link.href);
    
    // Show success message
    alert('✅ Attendance file downloaded!\n\n📁 Please save this file in one folder named "Attendance_Records".');
}

// ========================================
// EVENT LISTENERS
// ========================================

/**
 * Handle form submission for login
 */
document.getElementById('loginForm').addEventListener('submit', function(e) {
    e.preventDefault();
    
    const username = document.getElementById('username').value.trim();
    const password = document.getElementById('password').value;
    
    // Validate credentials
    const isValidUser = VALID_USERS.some(
    user => user.username === username && user.password === password
);

if (isValidUser) {

        // Success - get current timestamp
        const currentTime = new Date();
        const timestamp = formatTimestamp(currentTime);
        
        // Store attendance record
        attendanceRecords.push({
            username: username,
            timestamp: timestamp
        });
        
        // Show success message
        showMessage(`Welcome, ${username}! Login successful.`, 'success');
        
        // Show attendance section
        setTimeout(() => {
            showAttendanceSection(username, timestamp);
        }, 1000);
        
    } else {
        // Failed - play beep and show error
        playBeep();
        showMessage('❌ Invalid username or password. Please try again.', 'error');
        document.getElementById('password').value = '';
    }
});

/**
 * Handle download button click
 */
document.getElementById('downloadBtn').addEventListener('click', function() {
    const username = document.getElementById('displayUsername').textContent;
    const timestamp = document.getElementById('displayTimestamp').textContent;
    downloadAttendanceFile(username, timestamp);
});

/**
 * Handle logout button click
 */
document.getElementById('logoutBtn').addEventListener('click', function() {
    resetForm();
});

/**
 * Clean up audio context on page unload
 */
window.addEventListener('beforeunload', function() {
    if (audioContext) {
        audioContext.close();
    }
});